### ISSUE TITLE
Doesn't work out of the box (`Deno.close` is not a function)

### ISSUE THREAD

**Issue by Jollywatt** [joakimunge/denoliver#47]
Just trying this out with a fresh install, and receive this error, which seems internal:

```
error: Uncaught (in promise) TypeError: Deno.close is not a function
    ifconfig && (await Deno.close(ifconfig.rid))
                            ^
    at getNetworkAddr (https://deno.land/x/denoliver@2.3.1/utils/local-ip.ts:35:29)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async main (https://deno.land/x/denoliver@2.3.1/mod.ts:326:17)
```

Installed with:

```
❯ deno install --global --allow-net --allow-read --allow-write --allow-run https://deno.land/x/denoliver/mod.ts
Warning Implicitly using latest version (2.3.1) for https://deno.land/x/denoliver/mod.ts
```

Environment:

`macos-aarch64`
```
❯ deno --version
deno 2.1.4 (stable, release, aarch64-apple-darwin)
v8 13.0.245.12-rusty
typescript 5.6.2
```

**Comment by joakimunge** [comment]
Hey. Thanks for this! 

Looks like it is not compatible with the Deno 2.0 release. I am not actively developing this currently, but feel free to open a PR 🙏
