### ISSUE TITLE
Uncaught NotFound: No such file or directory

### ISSUE THREAD

**Issue by sarthaksavvy** [joakimunge/denoliver#7]
I run `denoliver ./src` but I got this error

`
error: Uncaught NotFound: No such file or directory (os error 2)
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendAsync ($deno$/ops/dispatch_json.ts:98:10)
    at async Object.open ($deno$/files.ts:37:15)
    at async Object.readFile ($deno$/read_file.ts:13:16)
    at async readFile (https://deno.land/x/denoliver/utils.ts:36:25)
    at async handleRouteRequest (https://deno.land/x/denoliver/mod.ts:55:16)
`

**Comment by joakimunge** [comment]
@sarthaksavvy How does your folder structure look? Do you have an `index.html` in root?

I'm so used to having that, I didn't think about that other people mignt not haha. Denoliver wants an `index.html` as an entrypoint right now, but I'm working on `v2` which will support `.js`-files as entrypoints.

**Comment by joakimunge** [comment]
@sarthaksavvy I just published a small improvement that will at least let you know if the file is missing. Better handling will come in v2 :)

https://github.com/joakimunge/denoliver/pull/8
